development:
  password: shptka_1fd9c0c39ee386060b19fed85d0d4643
  theme_id: "133259002049"
  store: developmentshin.myshopify.com
  ignore_files:
    - config/settings_data.json
    - /\.(txt|gif|bat)$/
    - "*.liquid___jb_tmp___"
    - "*.liquid___jb_old___"